CREATE TABLE TB_CUST 
(
  ID_CUST INT       (10) NOT NULL AUTO_INCREMENT
, NM_CUST VARCHAR   (50) NOT NULL
, ID_CATG INT       (10)
, CONSTRAINT TB_CUST_PK PRIMARY KEY (ID_CUST)
, CONSTRAINT TB_CUST_FK_01 FOREIGN KEY (ID_CATG) REFERENCES TB_CATG(ID_CATG)
) 
;

