
CREATE TABLE TB_CATG 
(
  ID_CATG INT    (10) NOT NULL AUTO_INCREMENT
, SG_CATG VARCHAR  ( 5) NOT NULL 
, DS_CATG VARCHAR  (20) 
, CONSTRAINT PK_TB_CATG_01 PRIMARY KEY ( ID_CATG ) 
, CONSTRAINT UC_TB_CATG_01 UNIQUE ( SG_CATG ) 
);

