Insert into TB_CUST (NM_CUST,ID_CATG) values ('Aliquam Eros Inc.','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Fringilla Est Mauris Inc.','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Aliquam Nec Enim PC','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Taciti Sociosqu Ad PC','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Tempus Eu Ligula Institute','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Nam Ac Ltd','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Elit Dictum Corporation','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Ac Inc.','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Dui Quis Accumsan LLC','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Nascetur Ridiculus Mus Industries','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Ut Incorporated','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Primis Institute','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Cursus Corp.','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Bibendum Ltd','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Eu Limited','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Nulla PC','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Phasellus LLP','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('In Mi Associates','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Nec Ligula Consectetuer Foundation','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Ornare Associates','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Lorem Limited','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Non Inc.','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Lacinia Company','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Nec Tempus Inc.','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Suspendisse Aliquet Incorporated','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Magnis Inc.','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Mauris Nulla Integer Consulting','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Cum Inc.','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Mauris Ltd','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Justo Proin Non Corporation','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('A Odio Semper LLC','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Aliquet Corporation','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Orci Luctus Industries','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Feugiat Lorem Ipsum Institute','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Molestie LLC','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Id Industries','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Elit Nulla Facilisi Inc.','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Ullamcorper Magna Sed Corporation','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Elit Nulla Facilisi Incorporated','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Sem Consulting','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Diam Luctus Lobortis Consulting','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Eleifend Associates','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Nam Consequat LLP','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Per Inceptos Hymenaeos Corp.','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Felis Institute','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Cras Inc.','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Metus Corporation','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Lacus Varius Institute','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Velit Incorporated','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Integer Id Magna LLC','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Lacinia At Iaculis Corporation','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Tristique Foundation','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Nulla Foundation','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Lacus Vestibulum Incorporated','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Nostra Per Inc.','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Pede Institute','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Pulvinar Arcu Et Consulting','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Elit Limited','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Fringilla Consulting','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Sit Incorporated','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Placerat Foundation','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Neque Morbi Quis Corp.','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Eu Tempor Erat Consulting','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Sapien Gravida Non Incorporated','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Erat Limited','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('A Felis Industries','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Consequat Lectus Sit LLC','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Arcu Sed Eu Consulting','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Quisque Nonummy Limited','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('In Sodales Corporation','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Mauris LLP','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Proin Non Massa LLP','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Ipsum Dolor Sit Inc.','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Sed Diam LLP','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Phasellus Nulla Integer Incorporated','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Lacus Company','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Tortor Inc.','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Dis Consulting','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Mauris Blandit Enim Associates','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Sapien PC','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Fermentum Convallis LLP','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Maecenas Ltd','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Inceptos Hymenaeos Foundation','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Vulputate Eu PC','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Non Bibendum Company','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Nec Diam Industries','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Ligula Nullam Feugiat Company','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Etiam Institute','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Ac Urna Ut Consulting','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Egestas A Scelerisque Associates','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Aliquam Adipiscing Limited','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Mi Ac Corp.','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Phasellus Foundation','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Eu Augue Porttitor Incorporated','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Elit Pharetra Industries','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Urna Suscipit Nonummy PC','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Nunc Sollicitudin Incorporated','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Pellentesque Foundation','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Massa Inc.','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Nulla Magna Incorporated','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Placerat Velit LLP','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Cras PC','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Metus Aenean Sed LLC','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Vitae Institute','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Convallis Inc.','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('In Corporation','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Mauris Foundation','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Sed Pede Ltd','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Nibh Corporation','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Semper Limited','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Lectus Corp.','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Nec Orci Company','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Mauris Blandit Company','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Sagittis Duis Gravida Industries','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Fusce Corp.','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Pellentesque Eget Dictum Institute','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Nullam Lobortis Quam Corporation','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Sed Ltd','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Suscipit Corp.','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Dignissim LLP','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Nam Nulla Magna Industries','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Pellentesque Ultricies Dignissim Company','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('In Associates','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Luctus Aliquet Odio Inc.','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Ipsum Institute','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Turpis Vitae Company','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Ipsum Consulting','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Nunc Industries','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Scelerisque Lorem Associates','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Nulla LLP','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Nam Nulla Magna Company','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Sapien Company','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Arcu Foundation','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Est Foundation','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Maecenas Mi Felis Incorporated','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Tellus Lorem Institute','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Gravida Sagittis Duis LLP','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Tempus Risus Donec Company','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Dis Parturient Corporation','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Dignissim Maecenas Consulting','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Proin Limited','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Mattis Semper Ltd','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Tempus Mauris Foundation','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Semper Tellus Id LLP','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Auctor Quis Ltd','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Magna Foundation','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Duis Risus Odio Associates','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Non Associates','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Tellus Sem Mollis Associates','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Dignissim Magna Incorporated','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Eleifend Foundation','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Eleifend Cras Sed Ltd','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Hendrerit A Associates','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Ut Consulting','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Dui Incorporated','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Tempor PC','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Vivamus Industries','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Vestibulum Ut Incorporated','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Velit Corp.','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Mauris Magna Institute','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Facilisis Facilisis Magna Associates','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Lacus Pede Sagittis Inc.','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Nunc Quisque Industries','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Volutpat Nulla Facilisis Consulting','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Adipiscing Lacus Ut PC','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Diam Eu Company','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Ipsum Dolor Corporation','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Eget Foundation','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Felis Incorporated','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Erat LLC','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Donec Dignissim Magna Company','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Proin Ultrices Industries','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Interdum Curabitur Dictum LLC','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Luctus Curabitur Egestas PC','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Varius Foundation','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Ut Nec Urna Associates','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Fermentum Fermentum Arcu Consulting','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Vulputate Nisi Associates','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Enim Gravida Sit Consulting','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Molestie Incorporated','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Dictum LLC','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Tincidunt Aliquam Foundation','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('In Foundation','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Elit Etiam Laoreet Industries','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Augue Institute','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Semper LLP','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Donec Est Ltd','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Elementum Sem LLP','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Nunc Interdum Feugiat Industries','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Dolor Sit Amet Institute','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Cursus Luctus Ipsum Corporation','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Fusce Inc.','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Et Pede Company','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Magna A Neque Company','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Quisque Institute','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Sed Inc.','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Urna PC','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Suspendisse PC','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Vel Arcu Eu Industries','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Magna Inc.','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Gravida Aliquam LLP','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Lorem Limited','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Ante Vivamus Corp.','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Molestie Sodales Mauris PC','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Lectus LLP','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Interdum Consulting','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Egestas Ltd','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Velit Incorporated','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Faucibus PC','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Nec Foundation','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Nulla In Ltd','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Pharetra Institute','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Dui In Sodales Limited','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Magna Lorem Incorporated','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Nisi Aenean Eget Limited','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Auctor PC','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Risus Quisque Libero Incorporated','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Convallis Incorporated','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Quis Pede Praesent LLP','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Enim Condimentum Ltd','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Nonummy Ut Molestie LLC','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Inceptos Hymenaeos Mauris Incorporated','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Pellentesque Corporation','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Non Hendrerit Institute','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Adipiscing LLC','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Ipsum Leo Corporation','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Ullamcorper Duis At Foundation','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Mauris Nulla Integer Inc.','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Enim Mi Tempor LLC','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Diam Duis Mi Corporation','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Et LLC','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Duis Associates','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Est Ac Inc.','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Erat Vitae Risus Limited','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Gravida Sit Amet Institute','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Gravida Ltd','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Eu Nibh Corporation','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Luctus PC','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Tristique Pharetra Quisque Corporation','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Felis Ullamcorper Viverra Corporation','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Elit Nulla Limited','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Pellentesque Ltd','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Accumsan Limited','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Aenean Inc.','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Curabitur Consequat Associates','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Arcu Vivamus Sit Institute','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Aliquam Adipiscing Lobortis Industries','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Lorem Ipsum Sodales Incorporated','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Vestibulum Foundation','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('A Corp.','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Sapien Nunc LLC','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Arcu Et Pede LLP','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Cursus Corporation','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Semper Rutrum Fusce LLC','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Ligula Nullam Enim LLP','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Pede Blandit Incorporated','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Eleifend Nec Company','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Ut Corporation','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Ipsum Cursus Incorporated','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Magna Company','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Quis Turpis Vitae Corporation','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Tincidunt Tempus Limited','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Commodo LLC','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Posuere Corp.','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Lectus Consulting','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Magnis Dis Parturient Ltd','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Orci Limited','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Quam Vel Sapien Limited','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Vehicula Pellentesque Tincidunt Corp.','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Cras Interdum Nunc Corporation','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Nulla Institute','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Ultrices Institute','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('At Pede Cras Associates','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Augue Eu Tellus Limited','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Consectetuer Adipiscing Corporation','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Pede Malesuada Vel Ltd','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Maecenas Malesuada Corp.','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Dictum Incorporated','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Pharetra Ut Pharetra Industries','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Sagittis Lobortis Mauris Corp.','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('In Felis Nulla Company','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Donec PC','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Lorem Auctor Quis Foundation','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Sit Amet Industries','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Vulputate Nisi LLC','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Lacus Mauris Non Associates','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Convallis Est Ltd','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Orci Luctus Et Ltd','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Sed Orci Corporation','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Ut Nulla Limited','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Libero Nec Ligula PC','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Gravida Mauris Ut Corporation','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Suspendisse Dui Fusce Industries','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Quis Lectus Corp.','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Sit Amet Risus LLC','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Elit Sed Consequat Foundation','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Risus Nunc LLC','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Sed Auctor Inc.','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Egestas Duis Company','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('At Risus Consulting','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Sagittis Duis PC','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Id Blandit At Industries','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Fusce Corp.','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Tristique Foundation','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Vestibulum Lorem Sit Limited','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Bibendum Associates','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Nunc Lectus Company','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Tellus Limited','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Dolor Donec Fringilla Limited','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Erat Neque PC','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Augue Eu Company','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Est Tempor Corp.','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Quam Institute','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Erat Nonummy PC','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Feugiat Placerat Limited','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Dolor LLP','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Ornare Tortor At Institute','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Senectus Et LLC','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Sed Company','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Eu Metus PC','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Placerat Incorporated','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Egestas Duis Ac Company','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Ut Ipsum Ac Associates','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Convallis In Cursus Corporation','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Aenean Sed Foundation','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Pede Blandit Congue Limited','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Non Industries','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Mollis Associates','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Dapibus Rutrum Justo PC','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Arcu Sed Eu Limited','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Justo LLP','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Duis Dignissim Tempor Corporation','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Eget Dictum Foundation','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Magnis Foundation','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Enim Mi LLC','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Metus Urna Convallis Associates','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Mus Consulting','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Urna Consulting','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Nibh Aliquam Ornare Associates','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Donec Tempus Lorem Consulting','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Nibh Foundation','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Senectus Et Company','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Pellentesque LLP','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Fusce Fermentum Consulting','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Pede Nonummy Ut LLC','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Scelerisque Scelerisque Dui Consulting','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('In Lobortis Tellus LLC','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Nec Tempus Mauris Limited','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Eu Ultrices Sit PC','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Id Erat Etiam Associates','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Molestie In Tempus Consulting','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Interdum Libero LLP','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Risus Ltd','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Velit Consulting','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Ut Limited','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Morbi Associates','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Condimentum Donec At Incorporated','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Donec Inc.','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Malesuada LLC','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Integer Mollis Integer Company','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Integer Sem Corp.','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Fusce Feugiat Lorem Inc.','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Pede Suspendisse Company','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Placerat Limited','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Arcu Vivamus Sit LLC','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Parturient Montes LLC','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Phasellus Nulla Integer Limited','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Cum Institute','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Auctor Inc.','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Praesent Associates','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Quam A Felis Inc.','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Dignissim Magna LLC','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Morbi Sit Amet Ltd','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Scelerisque Scelerisque PC','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Sed Auctor Limited','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Est Limited','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Lorem Eget Ltd','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Et Magnis LLP','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Est Consulting','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Massa Quisque Industries','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Ac Foundation','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Amet Faucibus Ut Ltd','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Nec Malesuada Foundation','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Lacus Quisque Foundation','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Id Ltd','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Elit LLC','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Non Dui Nec Foundation','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Ut Tincidunt LLP','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Nulla Company','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Varius Orci In Consulting','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Vestibulum LLC','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Tristique Aliquet Corp.','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Imperdiet Erat LLC','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Pulvinar Arcu Company','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Orci Industries','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Mattis Foundation','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Felis Inc.','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Arcu Incorporated','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Ipsum Dolor Corporation','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Facilisi LLP','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Sit LLC','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Sociis Natoque Inc.','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Ornare Lectus Ante LLP','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Viverra Maecenas Associates','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Nibh Aliquam Ornare Institute','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Lacus Consulting','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Ac Metus Vitae Incorporated','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Sit Amet Company','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Interdum Enim Non Institute','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Cursus Diam Corp.','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Enim Consequat Consulting','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Egestas Aliquam Nec Limited','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Enim Foundation','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Aliquam Eros Limited','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Nulla Integer Vulputate Inc.','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Aliquam Fringilla Cursus Corp.','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Molestie Pharetra Consulting','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Donec Est Industries','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Malesuada Fringilla LLP','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Ultricies PC','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Lacus Vestibulum Institute','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Metus Eu Erat LLP','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Sem Molestie Sodales Incorporated','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Mattis Integer Consulting','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Mauris Rhoncus Id Limited','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Maecenas Institute','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Ornare In Faucibus Foundation','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Nec Imperdiet Nec Incorporated','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Aliquam Consulting','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Fusce Corporation','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Ornare Facilisis Associates','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Vehicula Aliquet Libero LLC','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Nunc Commodo Auctor LLC','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Felis LLC','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Ut Institute','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Integer Tincidunt Consulting','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Tempor Diam Corporation','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Blandit Incorporated','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Arcu Aliquam Inc.','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Maecenas Industries','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Sodales Mauris Blandit Industries','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Libero Morbi Corporation','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Aenean Egestas Hendrerit Foundation','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Suspendisse Tristique Neque Industries','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Netus Et Malesuada Corporation','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Risus A Ultricies Corporation','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Vitae Odio Company','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Imperdiet Industries','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Interdum Nunc Sollicitudin Limited','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Lorem Vehicula Industries','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Interdum Curabitur Limited','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Proin Mi Company','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Integer Incorporated','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Cras Vehicula Ltd','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Augue Malesuada Malesuada Ltd','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Aliquam Erat Incorporated','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Massa Vestibulum Industries','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Proin Sed Turpis LLC','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Mauris Nulla Company','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Inceptos Hymenaeos Company','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Congue In LLC','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Consectetuer Corporation','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Morbi Tristique PC','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Ante Vivamus Non Incorporated','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Phasellus Dapibus Consulting','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Fames Associates','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Duis Elementum Institute','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Risus Donec Egestas LLC','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Tristique Company','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Nonummy Incorporated','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Diam Company','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Sagittis Augue Inc.','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Semper Institute','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Lorem Eu Metus Ltd','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Quisque Fringilla Euismod LLC','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Dapibus Id Associates','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Proin Ultrices Ltd','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Aliquet Consulting','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Nam Associates','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Vestibulum Industries','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Nec Corporation','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Ornare Corporation','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Consequat LLC','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Scelerisque Neque Sed Institute','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('A Corporation','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Et Corp.','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Convallis Convallis Foundation','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('At Nisi Cum Industries','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Facilisis LLC','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Quam Industries','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Sociis Natoque Penatibus Foundation','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Orci PC','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Consequat Inc.','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Enim Commodo Corp.','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Nam Ac Institute','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Blandit Enim Associates','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Risus Inc.','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Ipsum Non Arcu Incorporated','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('In Lobortis Tellus Limited','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Duis LLP','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('At Associates','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Tempus Associates','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Euismod Et Commodo LLC','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Mauris PC','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Condimentum Donec At Foundation','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Luctus Vulputate Nisi Limited','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Elit Curabitur Sed Limited','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Proin Ultrices Duis Limited','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('A Feugiat Tellus Consulting','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Pharetra Ut Corporation','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Dolor Fusce Feugiat Associates','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Eget Lacus Inc.','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Vitae Aliquam Eros Incorporated','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Ut Sagittis Lobortis Corp.','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Nec Mauris Company','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Rutrum LLP','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('At Auctor LLP','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Donec Tempus Lorem Corp.','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Varius Orci In Company','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Proin Incorporated','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Convallis Dolor Quisque Institute','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Mollis Integer Tincidunt Industries','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Imperdiet Erat Nonummy Institute','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Elit Elit Fermentum Industries','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Orci Associates','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Tellus LLP','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Quis Accumsan Consulting','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Dui Fusce Aliquam LLP','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Lectus Pede Et Inc.','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Morbi Tristique Corporation','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('In Hendrerit Incorporated','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Nisl Arcu Iaculis Corp.','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Odio Etiam Company','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Quisque Corp.','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Donec Sollicitudin Incorporated','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Enim Nunc Ut Corporation','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Ante LLC','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Ridiculus Mus Proin Consulting','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Ac Ipsum Phasellus Foundation','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Magna A Neque Foundation','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Quam Quis Consulting','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Vivamus Nisi Corporation','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Mauris Sit Amet Corporation','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Convallis PC','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Felis LLP','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Nisl Elementum PC','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Mauris Corporation','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Rutrum Inc.','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Phasellus Elit Pede Consulting','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Feugiat Consulting','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Aliquam Erat Volutpat Limited','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Lacus Aliquam Corp.','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Elit Consulting','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Arcu Sed Et LLP','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Iaculis Foundation','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Tincidunt Tempus Risus Foundation','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Taciti Sociosqu Ltd','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Ipsum Corporation','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Risus At Institute','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Sit Amet Massa Inc.','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Feugiat Metus Incorporated','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Ipsum PC','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Felis Purus Ac Inc.','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Lobortis Industries','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Neque Industries','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Morbi Metus Industries','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Rutrum Limited','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Massa Rutrum Magna LLP','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Tortor Nibh Sit PC','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Diam Institute','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Sit Amet Ltd','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Quis Urna Nunc PC','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Phasellus Industries','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Est Mauris Incorporated','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Amet Lorem Semper Corporation','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Tempus Mauris Erat Foundation','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Parturient Montes Consulting','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Nulla Ante Corporation','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Metus Sit Amet Institute','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Nisi Sem Semper Corporation','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Eleifend Nec Malesuada Inc.','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Elit Elit Fermentum Corp.','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Mauris Nulla Associates','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Nam Nulla Magna Industries','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Sed Industries','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Ante Ipsum Company','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Aliquam Fringilla Limited','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Sollicitudin Consulting','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Sed Eget Ltd','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Ante Nunc Mauris Inc.','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Enim Mauris Limited','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Tincidunt Nunc Ltd','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Dui Fusce Diam LLP','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Auctor Ullamcorper Nisl Ltd','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Condimentum Eget Volutpat Corp.','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Vivamus Nisi Ltd','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Diam Luctus Ltd','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Lorem Luctus Ut Inc.','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Purus Maecenas Institute','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Ligula Industries','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Molestie PC','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Mauris Integer Corporation','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Nunc Corp.','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Et Magnis Dis Company','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Elementum Dui Quis Limited','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Vivamus Euismod Foundation','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Tellus LLP','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Ac Metus Company','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Diam Luctus Consulting','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Tincidunt Consulting','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Egestas Rhoncus Proin Foundation','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Nunc Mauris Incorporated','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Sem Vitae Aliquam Industries','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Lacus Vestibulum Lorem PC','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Pede Suspendisse Industries','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Et Magnis Incorporated','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Sollicitudin Commodo Incorporated','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Rutrum Lorem Associates','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Egestas Sed Institute','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Dictum Magna Ut Incorporated','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Diam Inc.','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Dignissim Tempor Arcu Inc.','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Justo Corporation','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Magnis Dis LLP','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Massa Non Ante Corp.','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Eget Limited','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Scelerisque LLP','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Erat Vel Foundation','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Nunc Inc.','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('A Feugiat Tellus Corporation','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Vehicula Corporation','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Dolor Nonummy Ac Institute','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Sed Pede Cum Incorporated','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Faucibus Industries','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Sed Institute','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Nulla Consulting','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Montes Institute','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Ligula Donec Luctus Inc.','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Cursus In Industries','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Elementum Lorem Ut Industries','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Mauris Quis Turpis Company','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Ac Tellus Suspendisse Corporation','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Eget Massa Incorporated','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Quisque Nonummy Ipsum Industries','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Consectetuer Cursus LLC','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Rhoncus Institute','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Augue Institute','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Aptent Associates','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Metus Aliquam Institute','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Tellus Imperdiet Ltd','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Pharetra Ut Pharetra Company','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Erat Foundation','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Porttitor Eros Nec Consulting','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Purus In Company','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Cras Dolor Corporation','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Urna Nullam Associates','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Dolor Vitae Dolor Consulting','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Orci In Consequat Limited','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Metus Foundation','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Aliquam Enim Nec Inc.','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Eros Proin Ultrices Foundation','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Lobortis Quis Pede Corp.','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Dapibus Associates','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Enim PC','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Integer Vitae Associates','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Velit Cras Inc.','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Cras Institute','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Euismod Foundation','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Vivamus Nibh Dolor Corporation','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Libero Lacus Associates','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Arcu Curabitur Incorporated','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Egestas Corp.','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Ultricies Adipiscing Enim Incorporated','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Vehicula Incorporated','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Cras LLC','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Mi Company','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Eget Company','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Est Mauris Incorporated','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Lorem LLP','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Sed Leo Corporation','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Tincidunt Incorporated','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Dui Nec Ltd','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Lectus Consulting','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Tortor Dictum Institute','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Consequat Purus Maecenas Corp.','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Nonummy Ut Company','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Placerat Eget Venenatis Consulting','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Eu Nibh Company','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Cras Consulting','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Nunc Ac Corporation','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Ligula Consectetuer Ltd','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Dis Parturient Ltd','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Sed Pede Cum Institute','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Interdum Corp.','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Lobortis Augue Company','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Convallis Dolor Quisque Incorporated','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Tortor Dictum Eu Inc.','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Pellentesque Limited','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Aliquam LLP','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Enim LLP','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Tempus Limited','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Vestibulum Limited','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Arcu Nunc Consulting','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Eget Massa Corporation','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Erat Etiam Corp.','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Parturient Consulting','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Convallis Ligula Donec Associates','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Vehicula LLC','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Mus Proin Vel Industries','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Lobortis Industries','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Sed Leo Cras LLC','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Lacus Cras Interdum Institute','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Justo Company','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Feugiat Tellus Lorem Inc.','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Vulputate Foundation','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Libero Limited','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Aliquam Ornare Limited','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Nunc Quis Inc.','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Sit Amet Institute','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Suspendisse Tristique Institute','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Cum Sociis Incorporated','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Ut Eros LLP','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Leo In Lobortis Incorporated','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Nunc Limited','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Erat Foundation','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Et Ipsum Cursus PC','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Rutrum Associates','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Dolor Fusce Feugiat Corp.','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Pede Sagittis Augue Limited','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Nulla Tempor Augue Corporation','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Mauris Vel Turpis PC','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Dapibus Incorporated','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Nulla Corp.','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Elit Incorporated','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Felis PC','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Curae; Phasellus Ornare Consulting','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Ac Mattis Incorporated','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Sem Corp.','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Lorem Sit Amet Corporation','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Feugiat Sed Industries','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Erat Eget Corporation','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Facilisi Associates','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Velit Quisque Varius Institute','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Ornare Lectus Justo Consulting','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Elit Foundation','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('A Magna Lorem Corp.','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Sit Institute','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Orci Consulting','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Ante Dictum Mi Inc.','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Fermentum PC','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Pellentesque Company','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Dictum Placerat Limited','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Viverra Maecenas Iaculis Associates','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Vestibulum Nec Corp.','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Purus Accumsan Interdum Corp.','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Tincidunt Aliquam Incorporated','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Felis Orci Incorporated','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Elit Industries','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Lacinia Vitae Sodales Consulting','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Montes Nascetur PC','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Urna Nunc LLC','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Auctor Corp.','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Vel Arcu Consulting','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Ligula Elit Limited','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Lobortis Augue Scelerisque Ltd','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Eget Lacus Mauris Ltd','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Laoreet PC','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Mauris Corp.','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Magna Corporation','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Purus Gravida Sagittis PC','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Mi Lorem Vehicula PC','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Fringilla PC','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Sit Corp.','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Dictum Eu Placerat Limited','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Ante Dictum Inc.','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Ornare Sagittis Limited','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Quisque Porttitor Inc.','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Ut Sem Nulla Limited','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Aliquet Industries','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Aptent Industries','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Risus Varius PC','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Gravida Company','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Sem Institute','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('At Incorporated','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Tristique Institute','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Et Foundation','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Nisl Inc.','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Scelerisque Foundation','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Turpis Vitae Associates','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Scelerisque PC','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Cursus Institute','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Eros Non Corp.','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Sed Dui Fusce Ltd','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('At Velit Cras Limited','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Ante Limited','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Dolor Corp.','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Suspendisse Corp.','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Sit Amet Ultricies LLP','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Eros Nam Consequat Ltd','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Rhoncus Donec Est PC','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Lectus Cum Industries','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Imperdiet Dictum Inc.','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Dapibus Gravida Corporation','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Interdum Foundation','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Lobortis LLC','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Placerat Foundation','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Facilisis Industries','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Vestibulum Ut Industries','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Fringilla Ornare Placerat Foundation','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Nullam Limited','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Tempus Non Lacinia PC','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('In PC','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Quam Elementum At Industries','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Montes Nascetur Ridiculus Industries','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Luctus Vulputate Company','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Auctor Associates','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Iaculis Institute','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Sociosqu Ad Corp.','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Sem Eget Associates','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Sit Amet Diam Corp.','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Nam Porttitor Scelerisque Associates','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Eleifend Cras Sed Incorporated','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Id Libero Associates','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Adipiscing Mauris Molestie Corporation','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('A Mi Industries','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Eget Metus Corporation','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Vitae Consulting','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Faucibus Orci Luctus Associates','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Commodo Associates','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Ornare Elit Inc.','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Lorem Eget Corp.','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Enim Commodo LLC','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Ante Lectus Convallis LLP','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Nec Tempus Mauris Corporation','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Dolor Associates','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Lobortis Quam A PC','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Bibendum Ltd','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Libero Mauris Incorporated','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Tortor At Risus Limited','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Nunc Consulting','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Dignissim Tempor Institute','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Lectus Industries','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Sed PC','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Mauris Ltd','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Ut Quam Company','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Bibendum Donec Corporation','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Lorem Semper Ltd','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('A Auctor LLP','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Fusce Aliquet Foundation','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Eget Associates','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Mi Fringilla Mi Associates','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Arcu Eu Consulting','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Dolor Tempus Foundation','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Amet Ornare Lectus Industries','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Ac Mattis Associates','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Donec Feugiat PC','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Mauris Inc.','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Magna A Associates','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Arcu Curabitur Ut Corp.','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Lacus Consulting','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Sollicitudin Commodo Ipsum PC','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Nulla Donec LLC','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Non LLC','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Est Foundation','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('In Lorem Associates','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Fusce Aliquet Magna Ltd','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('At LLP','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Vel Limited','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Pellentesque Ut Ipsum Corporation','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Eget Metus Company','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Imperdiet Ullamcorper Duis Foundation','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('A Aliquet Associates','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Odio Sagittis Semper Corp.','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Nullam LLP','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Lacus Etiam Institute','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Massa Suspendisse Industries','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Id Erat Consulting','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Senectus Et Netus Inc.','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Vel Corp.','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Porttitor Eros Nec LLP','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Phasellus Foundation','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Fringilla Euismod Corp.','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Dui LLP','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Tortor Dictum Inc.','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Accumsan Sed Facilisis Limited','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Id Blandit At PC','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('In Company','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Id Risus Quis Company','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('At Limited','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Massa Non Associates','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Euismod In Dolor LLC','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Enim Corporation','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Pharetra Nibh LLC','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Tincidunt Orci Consulting','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Aenean Euismod Mauris Industries','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Eu Ligula Consulting','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Ornare Egestas Institute','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Sagittis Felis Donec PC','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Mattis PC','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Arcu Ac Orci Consulting','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Eget Magna Suspendisse Industries','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Mattis Integer Eu Ltd','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Vehicula Et Rutrum Corporation','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Nam Tempor Diam Incorporated','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Risus LLP','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Sem Vitae Aliquam Company','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('A Industries','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Donec Est Institute','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Lobortis LLC','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Ridiculus Mus Corp.','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Vel Industries','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Dui Lectus Limited','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Duis Volutpat Institute','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Natoque Penatibus Et Ltd','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Quam LLC','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Nisi Dictum Augue Company','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Porta Company','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Lorem Eu Metus Foundation','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Elementum At Institute','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Ut PC','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Lacus Associates','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Arcu PC','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Amet Ltd','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Metus Corp.','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Quisque Corp.','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Donec Elementum Lorem Company','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Et Ltd','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Semper Corp.','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Nullam Vitae Diam Limited','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Netus Et Ltd','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Gravida Molestie Associates','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Pharetra Nam LLC','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Senectus Et Netus Corporation','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Vitae Foundation','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Tristique Pharetra Institute','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Lacus Varius Associates','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Dignissim Ltd','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Maecenas Mi Associates','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Quam Foundation','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Malesuada Fames LLC','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Mauris PC','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Etiam LLC','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Mattis Semper Incorporated','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Tincidunt Pede Ltd','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Quisque Fringilla Euismod Industries','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Amet Massa Associates','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Facilisis Facilisis LLP','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Ultricies Corporation','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Curae; Phasellus Consulting','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Auctor Mauris Company','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Scelerisque Sed LLP','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Sed Ltd','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Vitae Odio Sagittis Industries','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Vehicula Limited','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Pede Corp.','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Fusce Mi Lorem Incorporated','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Libero Donec Consulting','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Amet Risus Donec PC','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Ridiculus LLP','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Elit Institute','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Eleifend Egestas Sed Foundation','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Pretium PC','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Rhoncus Foundation','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Montes Nascetur Ltd','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Dolor Quisque PC','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Ipsum Consulting','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Non Justo Consulting','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Dui Semper Et Foundation','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Dictum Phasellus Incorporated','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Mattis Velit Justo Consulting','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Habitant Morbi Tristique Institute','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('A Neque Corp.','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Luctus Et Ultrices Ltd','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Nunc Incorporated','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Dictum Inc.','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Ut Inc.','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Lectus Cum Corporation','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Proin Vel Nisl Incorporated','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Facilisis LLC','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Egestas Duis LLC','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Mauris Non Dui Corp.','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Dictum Limited','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Ante Blandit Ltd','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Duis Mi Enim Industries','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Tempor Company','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Cras Interdum Nunc Associates','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Lorem Tristique Aliquet PC','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Mus Limited','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Morbi Sit Corporation','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Tristique Ac Institute','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Ut Nec Urna Institute','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Habitant Inc.','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Rutrum Fusce Dolor LLP','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Mus Foundation','4');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Vestibulum Ante Ltd','3');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Lacus Nulla Company','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Id Associates','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Volutpat Ornare Facilisis PC','2');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Semper Pretium Incorporated','1');
Insert into TB_CUST (NM_CUST,ID_CATG) values ('Mauris Sagittis Foundation','3');
commit;
